name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
   
    steps:
    - uses: lukka/get-cmake@fix-issue-91, actions/checkout@v3
    - name: Build
      run: cargo build --verbose
